# Array of joint values with the following order:

# HeadYaw
# HeadPitch
# LHipYawPitch
# LHipRoll
# LHipPitch
# LKneePitch
# LAnklePitch
# LAnkleRoll
# LShoulderPitch
# LShoulderRoll
# LElbowYaw
# LElbowRoll
# RHipYawPitch
# RHipRoll
# RHipPitch
# RKneePitch
# RAnklePitch
# RAnkleRoll
# RShoulderPitch
# RShoulderRoll
# RElbowYaw
# RElbowRoll

float32[22] joints
---
uint8 result